// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdrijkmvpvuixsuywyen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkcmlqa212cHZ1aXhzdXl3eWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NTQyMzYsImV4cCI6MjA3NTQzMDIzNn0.KqwWKoto-rP00WAnmbqxcU95TbiJlN7TMpu07Q9fv58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});